/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.playMorphiaModel.impl;

import de.htwg.mdsd.playgenmodel.playMorphiaModel.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PlayMorphiaModelFactoryImpl extends EFactoryImpl implements PlayMorphiaModelFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PlayMorphiaModelFactory init()
  {
    try
    {
      PlayMorphiaModelFactory thePlayMorphiaModelFactory = (PlayMorphiaModelFactory)EPackage.Registry.INSTANCE.getEFactory(PlayMorphiaModelPackage.eNS_URI);
      if (thePlayMorphiaModelFactory != null)
      {
        return thePlayMorphiaModelFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PlayMorphiaModelFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PlayMorphiaModelFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PlayMorphiaModelPackage.DOMAINMODEL: return createDomainmodel();
      case PlayMorphiaModelPackage.PACKAGE_DECLARATION: return createPackageDeclaration();
      case PlayMorphiaModelPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case PlayMorphiaModelPackage.MORPHIA_MODEL: return createMorphiaModel();
      case PlayMorphiaModelPackage.ATTRIBUTE: return createAttribute();
      case PlayMorphiaModelPackage.TYPE: return createType();
      case PlayMorphiaModelPackage.DATA_TYPE: return createDataType();
      case PlayMorphiaModelPackage.IMPORT: return createImport();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Domainmodel createDomainmodel()
  {
    DomainmodelImpl domainmodel = new DomainmodelImpl();
    return domainmodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageDeclaration createPackageDeclaration()
  {
    PackageDeclarationImpl packageDeclaration = new PackageDeclarationImpl();
    return packageDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MorphiaModel createMorphiaModel()
  {
    MorphiaModelImpl morphiaModel = new MorphiaModelImpl();
    return morphiaModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataType createDataType()
  {
    DataTypeImpl dataType = new DataTypeImpl();
    return dataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PlayMorphiaModelPackage getPlayMorphiaModelPackage()
  {
    return (PlayMorphiaModelPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PlayMorphiaModelPackage getPackage()
  {
    return PlayMorphiaModelPackage.eINSTANCE;
  }

} //PlayMorphiaModelFactoryImpl
