/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.validation;

import de.htwg.mdsd.playgenmodel.validation.AbstractPlayMorphiaModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PlayMorphiaModelValidator extends AbstractPlayMorphiaModelValidator {
}
