/*
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPlayMorphiaModelScopeProvider extends DelegatingScopeProvider {
}
