/*
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.parser.antlr;

import com.google.inject.Inject;
import de.htwg.mdsd.playgenmodel.parser.antlr.internal.InternalPlayMorphiaModelParser;
import de.htwg.mdsd.playgenmodel.services.PlayMorphiaModelGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PlayMorphiaModelParser extends AbstractAntlrParser {

	@Inject
	private PlayMorphiaModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPlayMorphiaModelParser createParser(XtextTokenStream stream) {
		return new InternalPlayMorphiaModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public PlayMorphiaModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PlayMorphiaModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
