/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.ui;

import de.htwg.mdsd.playgenmodel.ui.AbstractPlayMorphiaModelUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PlayMorphiaModelUiModule extends AbstractPlayMorphiaModelUiModule {
  public PlayMorphiaModelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
