/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel;

import de.htwg.mdsd.playgenmodel.AbstractPlayMorphiaModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlayMorphiaModelRuntimeModule extends AbstractPlayMorphiaModelRuntimeModule {
}
