/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.scoping;

import de.htwg.mdsd.playgenmodel.scoping.AbstractPlayMorphiaModelScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PlayMorphiaModelScopeProvider extends AbstractPlayMorphiaModelScopeProvider {
}
