/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.ui.contentassist;

import de.htwg.mdsd.playgenmodel.ui.contentassist.AbstractPlayMorphiaModelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PlayMorphiaModelProposalProvider extends AbstractPlayMorphiaModelProposalProvider {
}
