/*
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PlayMorphiaModelRuntimeModule extends AbstractPlayMorphiaModelRuntimeModule {
}
