/*
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.validation

import org.eclipse.xtext.validation.Check
import de.htwg.mdsd.playgenmodel.playMorphiaModel.MorphiaModel
import de.htwg.mdsd.playgenmodel.playMorphiaModel.PlayMorphiaModelPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PlayMorphiaModelValidator extends AbstractPlayMorphiaModelValidator {
	
  public static val INVALID_NAME = 'invalidName'

	@Check
	def checkMorphiaModelStartsWithCapital(MorphiaModel model) {
		if (!Character.isUpperCase(model.name.charAt(0))) {
			warning('MorphiaModel name should start with a capital', 
					PlayMorphiaModelPackage.Literals.TYPE__NAME,
					INVALID_NAME)
		}
	}
	
}
