/*
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.ui.tests;

import com.google.inject.Injector;
import de.htwg.mdsd.playmorphiamodel.ui.internal.PlaymorphiamodelActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class PlayMorphiaModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PlaymorphiamodelActivator.getInstance().getInjector("de.htwg.mdsd.playgenmodel.PlayMorphiaModel");
	}

}
