/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.playMorphiaModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwg.mdsd.playgenmodel.playMorphiaModel.PlayMorphiaModelPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
