/**
 * generated by Xtext 2.9.1
 */
package de.htwg.mdsd.playgenmodel.playMorphiaModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Morphia Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwg.mdsd.playgenmodel.playMorphiaModel.MorphiaModel#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see de.htwg.mdsd.playgenmodel.playMorphiaModel.PlayMorphiaModelPackage#getMorphiaModel()
 * @model
 * @generated
 */
public interface MorphiaModel extends Type
{
  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link de.htwg.mdsd.playgenmodel.playMorphiaModel.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see de.htwg.mdsd.playgenmodel.playMorphiaModel.PlayMorphiaModelPackage#getMorphiaModel_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // MorphiaModel
